name: build-lcz-map

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Mondays 02:00 UTC weekly

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      LCZ4R_GITHUB_REPO: ByMaxAnjos/LCZ4r
      LCZ4R_GITHUB_REF: main
      GT_USE_EXACT: 'TRUE'
      ENABLE_MODIS: 'FALSE'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
      - name: Install R deps
        run: |
          Rscript -e 'install.packages(c("remotes","terra","sf","osmdata","jsonlite"))'
      - name: Run script
        run: |
          Rscript scripts/setup_and_run.R
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lcz-map-output
          path: |
            output/*
            output/MODIS/**
      - name: Commit updated outputs (if changed)
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          if git status --porcelain=1 | grep '^ M\|^?? output'; then \
            git add output/* && \
            git commit -m 'Update LCZ outputs [ci skip]' || echo 'Nothing to commit'; \
            git push; \
          else
            echo 'No output changes.'
          fi
